### ISSUE TITLE
Negative indexing

### ISSUE THREAD

**Issue by Luthaf** [bluss/rust-ndarray#152]
Do you have plans for negative indexing in arrays? Or is it even already possible? I did not found documentation about it.

I like the capacities of Fortran here, where you can write 

```fortran
! 3D Array with two range-based dimensions and one dimension going from 1 to 120
real :: array(-42:42, -42:42, 120) 
real :: b

b = array(-6, 18, 22)
```

It make expressing some algorithms much easier.

Rust support could look something like

```rust
let array = OwnedArray::from_elem((-42..42, -42..42, 120), 1.);
let b = array[(-6, 18, 22)];
```

That would require allowing `Range` as dimensions, and `isize` as indexes.

Edit: I just found a mention to `Ixs` for signed dimensions, but nothing about `Range` size. Is it related to that feature or not?

**Comment by bluss** [comment]
Using signed ranges as the size of axes is not something we are going to do. Negative indices can be used with slicing right now, negative indices count from the back of the axis, so `.slice(s![..-1, ..-1])` is an array slice of everything except the last row & last column.

**Comment by bluss** [comment]
In python, that would be `[:-1, :-1]`.

**Comment by Luthaf** [comment]
Ok, so this is more about Python style multi-dimensional arrays. I'll see if I can work around and express my algorithms differently, or if I need to implement my own multi-dimensional array. Thank you for the quick answer !

**Comment by bluss** [comment]
The previous *No* was certainly the most productive answer, and honest too, because it's the easiest to deliver on :wink:.

Either way, no promises, just some notes about what separates ndarray from being able to support it. If we make some changes incrementally, we might be able to generalize it enough to support it down the line.

- Split `Dimension` trait. Need to separate the notion of *the extent of each axis* from the notion of *a set of indices*.
