### ISSUE TITLE
Filter operation: convolution/correlation

### ISSUE THREAD

**Issue by b52** [bluss/rust-ndarray#199]
Convolution/correlation are common operations in signal and image processing. Since I tend to use `ndarray` now for most of my array-type data, it would be nice if it comes with a generic function for those operations.

It probably shouldn't be located in the core crate directly, but a child to contain such kind of operations. I currently have a implementation for the 2D case I move around, but I would be willing to contribute.

**Comment by bluss** [comment]
That sounds great, we might as well use separate crates for major extensions. For smaller kernel convolutions I'd guess there is a lot to win from having type level size information, but that's something we can punt on for now.

(Core numerics support must be in ndarray since it involves implementing traits like Add and so on, so I'm relatively happy with the included numerics as they are now).

**Comment by b52** [comment]
Ok, how should one now proceed?

**Comment by bluss** [comment]
What do you think about creating a new repo for the new crate? Go ahead and create it. It can be named something with ndarray- prefix and you and I can maintain it both. Can we determine scope and name now? Something like ndarray-signal, ndarray-convolve, or what you like?

**Comment by bluss** [comment]
Ok, this is now inactive.
