### ISSUE TITLE
(ArrayBase<S, Ix>) -> Vec<S::Elem>

### ISSUE THREAD

**Issue by Rufflewind** [bluss/rust-ndarray#207]
There is a `from_vec` function which consumes a `Vec<_>` to create a 1D array.

Is it possible to construct an inverse operation as well?

    (ArrayBase<S, Ix>) -> Vec<S::Elem>

**Comment by SuperFluffy** [comment]
Assuming your Array is contiguous, the easiest way is to use
`as_slice(&self)`, see also [here](
http://bluss.github.io/rust-ndarray/master/ndarray/struct.ArrayBase.html#method.as_slice),
and then either `Vector<_>::from(your_slice)` or `your_slice.to_vec()` on
the value in the `Option`.

If it is not contiguous, you can construct your vector by `iter(&self)`ing
over the Array and `collect(&self)`ing into a vector.

On Jul 27, 2016 01:40, "Phil Ruffwind" <notifications@github.com> wrote:

There is a from_vec function which consumes a Vec<_> to create a 1D array.

Is it possible to construct an inverse operation as well?

(ArrayBase<S, Ix>) -> Vec<S::Elem>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bluss/rust-ndarray/issues/207>, or mute the thread

**Comment by Rufflewind** [comment]
Note that I am looking for a function that constructs a `Vec<f64>` without copying, similarly to how `from_vec` works.

**Comment by bluss** [comment]
There's several options

1. create a vec that matches the logical (= row major) order of the elements
2. create a vec that matches the memory order of the elements
3. return whatever vec the array owns (The vec may have more elements than the array).

Only (3) always succeeds without copying. (2) Will often succeed without copying, but there are noncontiguous cases where it doesn't.

Here's an example: you can take a vec like `[0, 1, 2, 3, 4, 5, 6, 7]` and create an array that owns it that has the logical stride + shape so that the array is equal to `[[0, 2], [4, 6]]`.

```rust
use ndarray::prelude::*;
use std::iter::FromIterator;                                                 
let x = Array::from_shape_vec((2, 2).strides((4, 2)), Vec::from_iter(0..8)).unwrap();
println!("{:?}", x);
```
```
[[0, 2],
 [4, 6]] shape=[2, 2], strides=[4, 2]
```

**Comment by Rufflewind** [comment]
The one I'm looking for is (3).

**Comment by pegasos1** [comment]
How about 2d case,  Arraybase<S, (Ix,Ix)> -> Vec<Vec<S>>? Access owned vec and then take into account shape of array?

**Comment by bluss** [comment]
@Rufflewind ok, (1) being the natural "logical" case, we need to find a good name for the (3) operation.

@pegasos1  Note the `Array` always owns a `Vec<A>` where `A` is the element type, regardless of dimensionality, creating a nested vector would always be extra work.

**Comment by Rufflewind** [comment]
Well, you could restrict this function to work on 1-dimensional arrays only, which would make the operation more intuitive, right?  If one wants obtain a `Vec` from a multi-dimensional array, one would have to do the appropriate `reshape` first.

**Comment by bluss** [comment]
The same thing applies to 1-dimensional arrays (May use strides that are not 1 or even negative), so it doesn't really decrease the amount of surprise.

Special care will be taken in the API exactly because the common case is that the backing vector has equivalent logical content as the `Array`, but that is not guaranteed in general. See for example the existing method .as_slice_memory_order() for comparison, which is designed with some of the same thoughts in mind.
