### ISSUE TITLE
New dimension design in ndarray 0.7.x (upcoming)

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#238]
Summary of current state (EDIT: No longer current).

  - Big overhaul of dimensions: Add type ``Dim`` with aliases
    ``Ix1, Ix2, Ix3, ...`` etc for specific dimensionalities.
    Instead of ``Ix`` for dimension use ``Ix1``, instead of ``(Ix, Ix)`` use
    ``Ix2``, and so on.
  - The dimension type ``Dim`` supports indexing and arithmetic. See
    ``Dimension`` trait for new methods and inherited traits.
  - Constructors and methods that take tuples for array sizes, like ``Array::zeros,``
    ``Array::from_shape_vec``, ``.into_shape()`` and so on will continue to work
    with tuples.
  - The array method ``.dim()`` returns the dimension as it is. To get
    a tuple, use ``.dim_pattern()``.

Concerns:

- Can it be simplified?
- Are there any conversions or ergonomic things missing, that makes more old code compile?
- Should ``.dim()`` return a tuple like before, and instead we add a new accessor to the dimension?

**Comment by SuperFluffy** [comment]
I think it's time to unify `.dim()` and `.shape()`. Intuitively, `.dim()` should give the number of dimensions: 1, 2, 3, ..., n, while `.shape()` should give, well, the shape. I think this includes the serialization and the name in the struct: `dim` should be called `shape`.

**Comment by MaximilianR** [comment]
> I think it's time to unify .dim() and .shape(). Intuitively, .dim() should give the number of dimensions: 1, 2, 3, ..., n, while .shape() should give, well, the shape. This extends to serialization and the field name in ArrayBase: dim should be called shape.

+1 on `.shape`

numpy uses `ndim` for number of dimensions, which is explicit

**Comment by bluss** [comment]
There's a bit of a mess of terms, I can see that.

I think "dimension" is ok; Ix2 implements Dimension ("2D is a dimensionality"), and every pair (i, j) is an instance of Ix2 and so on.

ndarray also uses .ndim() -> usize, so we're fine there I think.

**Comment by vbarrielle** [comment]
Hello, as mentionned in vbarrielle/sprs#102, I'm trying to compile against the future version 0.7.

So far, using the `Ix1, Ix2` aliases works fine, but I've noticed another change that I didn't expect. I used to have code like this:

```rust
let scalar = some_vec[[index]];
```

but this won't compile any longer, with error `the trait bound `[usize; 1]: ndarray::NdIndex<ndarray::Dim<[usize; 1]>>` is not satisfied`. It looks like now the proper way of indexing a one dimensional vector is `some_vec[index]`, which is clearly nicer, but I was wondering if breaking this was intentional, or if you intended to keep the possibility to index with a length one array for consistency with indexing arrays with more dimension, where the ``[[]]`` syntax is still required.

**Comment by bluss** [comment]
That's not an intentional break, great report, I'll fix it now. I'm sure that indexing with just `usize` was fine before too.

**Comment by vbarrielle** [comment]
Ok, no problem with the latest commit. Thanks!

**Comment by bluss** [comment]
Improvements in #239, also published 0.7.0-alpha.0 and so docs for the new things will be on docs.rs.

index/dimension overview https://docs.rs/ndarray/0.7.0-alpha.0/ndarray/struct.ArrayBase.html#indexing-and-dimension
