### ISSUE TITLE
Consider factoring Serde support into a separate crate

### ISSUE THREAD

**Issue by dtolnay** [bluss/rust-ndarray#274]
Similar to how [`hyper_serde`](https://crates.io/crates/hyper_serde) and [`url_serde`](https://crates.io/crates/url_serde) work.

Users would need to select the ndarray_serde version that matches their ndarray version and serde version, then use it with Serde's `with` attribute:

```rust
#[macro_use]
extern crate serde_derive;

extern crate ndarray;
extern crate ndarray_serde;

#[derive(Serialize, Deserialize)]
struct S {
    bluss: String,
    #[serde(with = "ndarray_serde")]
    data: Array2<u8>,
}
```

If most users use ndarray with Serde, don't do this.

If few users of ndarray use it with Serde, this mitigates the triple pace issue brought up in https://github.com/bluss/rust-ndarray/pull/271#issuecomment-283812239.

**Comment by bluss** [comment]
Then the Array type no longer implements the serialization traits, which is less serde integration. Not easy to pick, unless all use would be through derived impls.

**Comment by bluss** [comment]
@SuperFluffy what do you think about this? It's not ideal, but I think I want to do this.

However, if serde plans on going 1.0 and not bumping for a while, sticking with serde as it is seems best.

**Comment by SuperFluffy** [comment]
For my personal use case, it would actually have been great to separate the
serde implementation into a different crate. I don't want to update serde,
but updating ndarray would be great, especially with some of the changes
coming.

With separate crates it would be much easier to have older versions of
serde also support newer versions of ndarray and vice versae.

So I think I'm in favor of splitting it up.

On Mar 25, 2017 15:48, "bluss" <notifications@github.com> wrote:

@SuperFluffy <https://github.com/SuperFluffy> what do you think about this?
It's not ideal, but I think I want to do this.

However, if serde plans on going 1.0 and not bumping for a while, sticking
with serde as it is seems best.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bluss/rust-ndarray/issues/274#issuecomment-289216301>,
or mute the thread

**Comment by dtolnay** [comment]
Closing in favor of #314.
