### ISSUE TITLE
column vector

### ISSUE THREAD

**Issue by klangner** [bluss/rust-ndarray#275]
Lets say that I have two 2-dimensional matrices A and B. And I want to select first column from A matrix and add this column to the all columns of B.
I don't know how to do it. The problem is that when I use A.column() function I will get back row Vector. I would expect column vector here. 
Even if I call transpose on this vector it still gives row vector. (So transpose do nothing for vector.)
Is this by design?

Any tips what is the correct way to add vector to all column in 2D matrix?
Thanks in advance.

**Comment by bluss** [comment]
It could be said to be by design.

On one hand they are not row/column vectors, just 1D vectors. Broadcasting rules make them align with the rows of a 2D array though.

You can reshape a vector of length n to shape (n, 1) for example, to make it truly be a column as a 2d array. Adding the (n, 1) array with a (n, x) array will work like desired.

You could also transpose a view of the big array temporarily, so that the row alignment turns into column alignment. Arguably this is not as simple as it should be:

if `column` is a 1d array:

```rust
*&mut array.view_mut().reversed_axes() += column
```

The mess with `*&mut` is because `+=` is only available to “lvalues” in Rust. An alternative is to use the .add_assign method from the AddAssign trait manually, or break it up into several lines.

```rust
let mut tarray = array.view_mut().reversed_axes();
tarray += column;
```

I'm open to your vision, is there an achievable better interface here?

**Comment by klangner** [comment]
Thanks for the answer :-) I will use reshape.

I just checked numpy and it looks that it behaves the same. It surprise me since I used it a lot and never had this kind of problems. It st somehow easier in Python. But that's because of the language not this library design I think.
And the error messages like (when trying to define range):
```
the trait `std::convert::From<std::ops::Range<usize>>` is not implemented for `ndarray::Si`
```
doesn't help :-)

Regarding the design of the API. I like. And I think this is very good and useful library.
Most of the problems I have are related to Rust (I just started to learn it) not to this library.

I think I will use this library a little bit more, learn Rust and then try to give any feedback.
