### ISSUE TITLE
Reimplement IxDyn

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#285]
It's using a Vec right now; it should be simplified.

- Use “small vec” optimization; no allocation for small dimensions
- Cap maximum number of axes to some limit (u16?)

**Comment by Robbepop** [comment]
I think even a maximum dynamic dimensionality representable by `u8` would never be used anywhere since the element number grows exponentially with the dimensionality and even 2^100 bytes memory usage is already really out of bounds.

The idea to use another data structure than `Vec` sounds also good since `Vec` offers much more flexibility (growing and shrinking) that is not required at all. Even a `Box<[usize]>` would be a better fit.

Using `SmallVec` has the advantage of having no dyn memory alloc up to a certain size but with this approach we could model the whole entirety of `Ix` and besides that `SmallVec` is again growable and shrinkable. Better would be a `SmallBoxedSlice` which does not exist, ... yet.

**Comment by bluss** [comment]
This is supported right now. I agree it's pointless. In this case all dimensions are 1, so the len of the array is 1 element, even if it has 1 << 16 axes.

```rust
Array::zeros(vec![1; 1 << 16])
```

I'd like to do a custom implementation here, SmallVec for example is too bulky, would not be a big gain.

**Comment by Robbepop** [comment]
Yeah it is a real edge case but for a general approach you may be right!
