### ISSUE TITLE
Impl From<&[A]> for Array1<A>

### ISSUE THREAD

**Issue by JP-Ellis** [bluss/rust-ndarray#360]
At the moment, Array1 has
```
impl<A> From<Vec<A>> for Array1<A>
```
but it does not have 
```
impl<A> From<&[A]> for Array1<A>
```

Is there a reason for this?  The latter implementation seems like it would be more general (especially given that `Vec<A>` can easily be converted to `&[A]`).  The only thing perhaps is that `&[A]` will probably require to `A` to be clonable.

If there is no reason for the lack of implementation, I'm happy to create a new pull request for this.

**Comment by bluss** [comment]
Ownership semantics matter, not just ownership of single elements but of a region of memory and thus `From<Vec<A>>` has an important difference to the slice variant -- the from vec operation computes in O(1) time with no copying or reallocation.

I'm not 100% sure we should add this -- `ArrayView::from(&[A])` already exists (also computes in O(1) time). Users could figure out the other details and the copying needed. Before I've mostly liked to use `From` for simple transformations of equivalent types like this -- but I guess From is getting wide use for all kinds of transformations in the Rust ecosystem in general?

**Comment by Robbepop** [comment]
The computation overhead part is especially important when it comes to an implementation of `From` for any type since it is used so widely in generic code via `Into<T>` that it could significantly degrade performance oriented generic programming in Rust if too many types do high-overhead computations on `From` impls.

For this we can still have explicit methods that (not only via doc) tell users about their costs instead of promoting further impliciteness as it is done in todays C++ code with very intransparent results.

**Comment by bluss** [comment]
Ok, I think we've decided to not do this for the time being, motivation is that we want to not obscure the cost of copying; the same operation is easily reachable by composing two methods or functions instead.
