### ISSUE TITLE
How to resize an ndarray?

### ISSUE THREAD

**Issue by bnbowman** [bluss/rust-ndarray#387]
Maybe I'm just not seeing it, but is there a way to resize an ndarray with the current API?  I want to be able to dynamically add rows to a data matrix, but I'm not sure how,

**Comment by bluss** [comment]
It's not resizable, not implemented. It's mentioned early in the docs :smile:

**Comment by bluss** [comment]
I'll close this. I want to support row by row and similar types of growth, and we need an issue with an actionable plan or request for this.

**Comment by Pzixel** [comment]
Please, consider resizing this guy. For example i'm looking for implementing adjacent matrix  so I need to resize it when new vertices comes.

**Comment by Pzixel** [comment]
I'm just talking that it's one of main features for such an array, and fixed-sized arrays are quite impracticable in real world tasks.

Implementation may be naive, such as "allocate new guy and copy every element in loop", but it has to be, imho.

I don't have any better ideas right now, just a knowledge that this is ultimate requirement from real tasks.

**Comment by bluss** [comment]
I disagree, take as example the successful library called NumPy (Python) that implements arrays that don't grow either. Current applications of ndarray are real tasks, too.

**Comment by jturner314** [comment]
@Pzixel In case you didn't see them, there are the [`stack![]` macro](https://docs.rs/ndarray/0.11.2/ndarray/macro.stack.html) and [`stack()` function](https://docs.rs/ndarray/0.11.2/ndarray/fn.stack.html), which work by allocating a new array and copying every element from each source array. This sounds like what you're describing as the "naive implementation". For more complicated operations than stacking along a single axis, it's possible to allocate a new array and use a combination of [`.slice_mut()`](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.slice_mut) and [`.assign()`](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.assign) to copy other arrays into pieces of the new array.

The limitation is that it's currently not possible to resize an array *in-place* (resizing by growing an existing allocation), which is also true of NumPy.

For an adjacency matrix, it needs to grow in two dimensions simultaneously as vertices are added, so the `stack` macro/function aren't ideal. You could either:

1. Allocate a new array each time there's a new vertex and copy the old data into the upper-left square of the new array with `new.slice_mut(s![..-1, ..-1).assign(&old)`. This requires a new allocation each time, which isn't great, but copying all of the data (or at least all except for the first row/column) is the only possible way to enlarge a contiguous row-major/column-major array in two dimensions (because of the way the elements are laid out in memory).
2. Allocate a very large array at the beginning filled with zeros that's big enough to handle the largest possible graph you're working with, so you never have to resize it.

If you're doing a lot of resizing, a different representation might be better (e.g. an adjacency list). [`petgraph`](https://github.com/bluss/petgraph) provides an adjacency list graph type.

**Comment by Pzixel** [comment]
@jturner314 thank you for your post.

By "naive" implementation I meant your `new.slice_mut(s![..-1, ..-1).assign(&old)`. Now I'm looking toward single dimension array that represents matrix in following way:

```
0 |1 |8 |9 |
__|  |  |  |
3  2 |7 |10|
_____|  |  |
4  5  6 |11|
________|  |
15 14 13 12|
___________|
```
resulting in possibility to resize almost in-place. When we should add more items we just allocate `2n-1` more items and fill them in described manner. I'l come later with exact code. Don't know if it worth to add into the lib (probably it doesn't), however it should fit 2D resize need.

**Comment by Pzixel** [comment]
I did it, but it seems to be unusable for non-square matrices, so I don't bother you anymore.

In case someone is interested in solution:

```
use std::ops::{Index, IndexMut};

pub trait Index2D {
    fn get_indices(&self) -> &[usize; 2];
}

impl Index2D for [usize; 2] {
    fn get_indices(&self) -> &[usize; 2] {
        self
    }
}

pub struct AdjacencyMatrix<T> {
    n: usize,
    value: Vec<T>,
}

impl<T: Default + Clone> AdjacencyMatrix<T> {
    pub fn new(n: usize) -> Self {
        Self {
            n,
            value: vec![T::default(); n * n],
        }
    }

    pub fn grow(&mut self, n: usize) {
        self.n += n;
        let newlen = self.value.len() + 2 * self.n - 1;
        self.value.resize(newlen, T::default());
    }
}

impl<T> Default for AdjacencyMatrix<T> {
    fn default() -> Self {
        Self {
            n: 0,
            value: Vec::new(),
        }
    }
}

impl<T, Idx: Index2D> Index<Idx> for AdjacencyMatrix<T> {
    type Output = T;

    fn index(&self, index: Idx) -> &<Self as Index<Idx>>::Output {
        let indices = index.get_indices();
        let linear_index = index_linear(indices[0], indices[1]);
        self.value.index(linear_index)
    }
}

impl<T, Idx: Index2D> IndexMut<Idx> for AdjacencyMatrix<T> {
    fn index_mut(&mut self, index: Idx) -> &mut <Self as Index<Idx>>::Output {
        let indices = index.get_indices();
        let linear_index = index_linear(indices[0], indices[1]);
        self.value.index_mut(linear_index)
    }
}

fn index_linear(i: usize, j: usize) -> usize {
    let s = i.max(j);
    if s % 2 == 0 {
        (s * s + s) + i - j
    } else {
        (s * s + s) + j - i
    }
}

impl<T: Debug> Debug for AdjacencyMatrix<T> {
    fn fmt(&self, f: &mut Formatter) -> Result<(), Error> {
        writeln!(f, "Adjacency matrix")?;
        for i in 0..self.n {
            for j in 0..self.n {
                write!(f, "{:?} ", self[[i, j]])?;
            }
            writeln!(f)?;
        }
        Ok(())
    }
}
```

It allows to add columns and rows into the matrix via just extending underlying vestor, without copying all elements one by one.
