### ISSUE TITLE
s! expands to unsafe code

### ISSUE THREAD

**Issue by Enet4** [bluss/rust-ndarray#403]
Since version 0.11.0, the `s!` macro expands to code containing unsafe code blocks. Since they are expanded at the destination, code with the `#![deny(unsafe_code)]` unsafe-free badge will no longer compile.

What can be done to mitigate this? Can the unsafe details be encapsulated to a crate-scoped function?

**Comment by bluss** [comment]
First thought is that we use an attribute in the macro to allow unsafe code. The user crate can use `forbid(unsafe_code)`, and then we can't do anything and I think it is correct to stop the compile then.

cc @jturner314

**Comment by jturner314** [comment]
Fwiw, it isn't *strictly* necessary for the method in question (`SliceInfo::new_unchecked()`) to be unsafe. If `out_dim` and `indices` don't match, `slice_move` will generate incorrect output but it won't do anything *unsafe* or return an array/view that could reference illegal memory. That said, I prefer keeping it unsafe because it's nice for code to be able to depend on `out_dim` and `indices` matching.

By the way, it's not possible to use a crate-scoped function because macros can only use the public API. (The scope of the expanded macro is wherever it appears in the client code.)

The best approach seems to be to use `#[allow(unsafe_code)]` in `s![]`. (For example, this is the approach `lazy_static!` takes.) Unfortunately, attributes can only be applied to items, so `s![]` would need to create a temporary wrapper function for `SliceInfo::new_unchecked()` just to be able to use `#[allow(unsafe_code)]`. I assume adding a wrapper function is essentially free (will be compiled away) if we use `#[inline(always)]`, but I'm not really sure. I'm thinking of [something like this](https://github.com/jturner314/rust-ndarray/commit/c6c7afb998e284d9449876c22d2e7733cd1856d2).

**Comment by bluss** [comment]
Please don't use a function, attract on the match block should be fine

**Comment by jturner314** [comment]
I tried putting `#[allow(unsafe_code)]` on the `match`, but the compiler says "error: attributes on non-item statements and expressions are experimental. (see issue #15701)". (On the nightly compiler, it's telling me to add `#![feature(stmt_expr_attributes)]`.) Is there another way to avoid creating a function?

**Comment by Enet4** [comment]
Unless I overlooked something, `#[allow(unsafe_code)]` on a match statement should indeed work. I replicated this in the playground [here](https://play.rust-lang.org/?gist=f0ffdf7e7fa23a9cb04270d146bc9ebb&version=stable).

**Comment by bluss** [comment]
Weird, we can have attributes on single statements. It's a bit inconsistent

**Comment by bluss** [comment]
@Enet4 I believe the following code is where we meet the problem -- and it matches how the match is used in ndarray. This doesn't compile on stable:

```rust
#![deny(unsafe_code)]

fn main() {
    let x = 
        #[allow(unsafe_code)]
        match () {
            _ => unsafe {
                let _: u32 = std::mem::zeroed();
            },
        };
}

```

**Comment by Enet4** [comment]
Would a macro allow us to just wrap everything around a new block like this?

```
#![deny(unsafe_code)]

fn main() {
    let x = {
        #[allow(unsafe_code)]
        match () {
            _ => unsafe {
                let _: u32 = std::mem::zeroed();
            },
        }
    };
}
```

**Comment by jturner314** [comment]
It looks like it's possible to add the attribute [directly to the `unsafe` block](https://github.com/jturner314/rust-ndarray/commit/6cdf3b9220765b1c611ce581bd30d90fec7ca59f).
